### ISSUE TITLE
{"error":"From is required"} after fresh install

### ISSUE THREAD

**Issue by yagobski** [o15y/staart#374] opened 2019-09-27 22:25 UTC
I just install Staart and i get this error when i register the first user.

{"error":"From is required"}

I think is linked to problem with email. It is normal that the row primaryEmail have int(12) in staart-users ?

**Comment by AnandChowdhary** [comment] 2019-09-27 22:27
This seems like the error is because the "From" email is not specified, when sending an email confirmation. Do you have the right environment variables in place? Please see https://github.com/o15y/staart/blob/master/.env.example and make an `.env` file.

As you'll see in https://github.com/o15y/staart/blob/master/src/config.ts#L60, not having an `SES_EMAIL` will throw this error.

**Comment by yagobski** [comment] 2019-09-27 22:28
Yes i am using the right .env.
I think is linked to problem with email. It is normal that the row primaryEmail have int(12) in staart-users ?

**Comment by AnandChowdhary** [comment] 2019-09-27 22:46
Alright, let's have a look. Can you send me a more detailed error, maybe from the console?

Yes, the `primaryEmail` field stores the ID of the email record in the `email` table, not the actual email address string.

**Comment by yagobski** [comment] 2019-09-27 22:47
There is no error only [object Object] in the console

**Comment by AnandChowdhary** [comment] 2019-09-27 22:59
Alright, here's what I'll do. I have [a talk tomorrow](https://cloud.womenwhocode.dev) but after that, I'll record a screencast of cloning Staart and setting it up and upload it over the weekend.

**Comment by yagobski** [comment] 2019-09-27 23:00
Ok thank you very much for your help. It will be good for other people.
The project is very good. I really like the idea

**Comment by araduti** [comment] 2019-09-28 13:42
That would be great! @AnandChowdhary ! I managed to setup both staart and staart-ui. Register account works, reset password works. Login goes in a loop and I get "invalid-token' if I debug. :/ - I'm sure it;s something simple I missed...

**Comment by AnandChowdhary** [comment] 2019-09-28 14:01
Yes, this is because the Axios token is invalid. Just remove the X-Api-Key from your axios.config.ts in Staart UI to fix.

**Comment by yagobski** [comment] 2019-09-28 23:54
For me still i get this error: [object Object]
I install it in another server. No way to make it work.

**Comment by araduti** [comment] 2019-09-29 04:58
Thanks @AnandChowdhary, knew it was something easy. All good now. @yagobski  - I had that too, it was because of AWS SES, I had it in sandbox (default when you create account) and I was trying to register an unapproved domain e-mail.

**Comment by AnandChowdhary** [comment] 2019-09-30 00:04
Thanks, @araduti! @yagobski, can you check if applying for production (from SES sandbox) or using a sandbox-approved email solves your problem?

**Comment by yagobski** [comment] 2019-09-30 00:46
@AnandChowdhary  I already use the information in my .env. I create accounts for that but not solve my problem. I will try to debug it and let you know.

**Comment by AnandChowdhary** [comment] 2019-09-30 18:41
I've added a small test for both email and Redis configuration. Now, when you run Staart, it'll test your configurations. If your AWS SES configuration is invalid (like @araduti suggested), then you'll see the following in your console:

![Screenshot of error message](https://user-images.githubusercontent.com/2841780/65906317-2f8e9e80-e377-11e9-84c5-02768dc0e439.png)

If you don't see this message and still get this error, it's probably something else. Can you `pull` to the most recent version and try?

**Comment by araduti** [comment] 2019-10-01 07:39
Awesome @AnandChowdhary ! I'm sure it will save other headaches.  Maybe you can add the  X-Api-Key test as well, or add it to the documentation ?

**Comment by AnandChowdhary** [comment] 2019-10-19 23:51
This was added on the https://staart.js.org/ui website. I think I should close this issue for now, since nobody else is able to reproduce it. I'll reopen it if we're sure it's not an AWS SES issue. You can test that by, instead of sending real emails, `console.log`ging them.

**Closed by AnandChowdhary** 2019-10-19 23:51 UTC
Labels: bug
